apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    targetRevision: "1.0.10"
    repoURL: https://charts.bitnami.com/bitnami
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
