# kubeseal --controller-name=sealed-secrets --controller-namespace=sealed-secrets
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default

  source:
    chart: sealed-secrets
    targetRevision: "1.0.10"
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      parameters:
        - name: fullnameOverride
          value: sealed-secrets-contoller # sealed-secrets-contoller is kubeseal CLI default controller name
        - name: namespace
          value: kube-system

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
